In [2]:
import numpy as np

In [3]:
# list
number = [1, 2, 3, 4, 5]

In [4]:
print(number)
type(number)

[1, 2, 3, 4, 5]


list

In [5]:
# numpy array
numbers = np.array([1, 2, 3, 4, 5])

In [6]:
print(numbers)
type(numbers)

[1 2 3 4 5]


numpy.ndarray

In [7]:
number

[1, 2, 3, 4, 5]

In [8]:
numbers

array([1, 2, 3, 4, 5])

In [9]:
# multi-dimensional array
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
#
integers = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
floats = np.array([0.1, 0.2, 0.3, 0.4])
floats

array([0.1, 0.2, 0.3, 0.4])

In [17]:
integers.dtype

dtype('int64')

In [18]:
floats.dtype

dtype('float64')

In [19]:
integers.ndim # number of dimensions

2

In [20]:
floats.ndim # number of dimensions

1

In [21]:
print(integers.size) # number of elements in the array
print(integers.itemsize) # size of each element in bytes
print(integers.size *  integers.itemsize) # total size of the array in bytes

6
8
48


In [22]:
print(floats.size) # number of elements in the array
print(floats.itemsize) # size of each element in bytes
print(floats.size *  floats.itemsize) # total size of the array in bytes    

4
8
32


In [26]:
for row in integers:
    for column in row:
        print(column, end=" ")
    print()

1 2 3 
4 5 6 


In [29]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a.dtype) # data type of the array --> answer is int64 because it is an integer array and the default integer type in numpy is int64
print(a.ndim) # number of dimensions --> answer is 2 because it is a 2D array
print(a.shape) # shape of the array (number of rows, number of columns) --> answer is (2, 5) because it has 2 rows and 5 columns
print(a.size) # total number of elements in the array --> answer is 10 because it has 10 elements
print(a.itemsize) # size of each element in bytes --> answer is 8 because it is an integer array and each integer takes 4 bytes
print(a.size * a.itemsize) # total size of the array in bytes --> answer is 40 because it has 10 elements and each element takes 4 bytes, so total size is 10 * 4 = 40 bytes

int64
2
(2, 5)
10
8
80


In [31]:
# Filling arrays with specific values
np.zeros(5) # creates a 1D array of length 5 filled with zeros

array([0., 0., 0., 0., 0.])

In [33]:
np.ones((2, 4)) # creates a 2D array of shape (2, 4) filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.ones((2, 5), dtype=int) # creates a 2D array of shape (2, 5) filled with ones and data type is integer

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.ones((2, 4), dtype= float) # creates a 2D array of shape (2, 4) filled with ones and data type is float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.full((3, 5), 33) # creates a 2D array of shape (3, 5) filled with the value 33

array([[33, 33, 33, 33, 33],
       [33, 33, 33, 33, 33],
       [33, 33, 33, 33, 33]])

In [ ]:
np.arange(5) # creates a 1D array of length 5 filled with values from 0 to 4

array([0, 1, 2, 3, 4])

In [38]:
np.arange(5, 10) # creates a 1D array of length 5 filled with values from 5 to 9

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 1, -2) # creates a 1D array of length 5 filled with values from 10 to 2 with a step of -2

array([10,  8,  6,  4,  2])

In [40]:
np.linspace(0.0, 1.0, num=5) # creates a 1D array of length 5 filled with values from 0.0 to 1.0 with equal spacing

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [41]:
#
np.arange(1, 21) # creates a 1D array of length 20 filled with values from 1 to 20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
np.arange(1, 21).reshape(4, 5) # creates a 2D array of shape (4, 5) filled with values from 1 to 20

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
np.arange(1, 100001).reshape(4, 25000) # creates a 2D array of shape (4, 25000) filled with values from 1 to 100000

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]],
      shape=(4, 25000))

In [45]:
np.arange(1, 100001).reshape(100, 1000) # creates a 2D array of shape (100, 1000) filled with values from 1 to 100000

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]],
      shape=(100, 1000))

In [47]:
#
import random
%timeit rolls_list = [random.randrange(1, 7) for i in range(0, 6_000_000)]

7.24 s ± 751 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [48]:
#
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

195 ms ± 32.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [49]:
# Array Operators
numbers = np.array([1, 2, 3, 4])
numbers

array([1, 2, 3, 4])

In [50]:
numbers * 2 # multiplies each element in the array by 2

array([2, 4, 6, 8])

In [51]:
numbers + 2 # adds 2 to each element in the array

array([3, 4, 5, 6])

In [52]:
numbers ** 3 # raises each element in the array to the power of 3

array([ 1,  8, 27, 64])

In [54]:
numbers

array([1, 2, 3, 4])

In [55]:
numbers += 10

In [56]:
numbers

array([11, 12, 13, 14])

In [57]:
#
numbers2 = np.linspace(1.1, 5.5, 4)
numbers2

array([1.1       , 2.56666667, 4.03333333, 5.5       ])

In [58]:
numbers * numbers2 # Broadcasting: multiplies each element in the first array by the corresponding element in the second array, if the shapes are compatible for broadcasting. In this case, the first array has shape (4,) and the second array has shape (4,), so they are compatible for broadcasting and the result is a new array where each element is the product of the corresponding elements in the two arrays.

array([12.1       , 30.8       , 52.43333333, 77.        ])

In [59]:
numbers >= 13 # returns a boolean array where each element is True if the corresponding element in the original array is greater than or equal to 13, and False otherwise

array([False, False,  True,  True])

In [60]:
numbers < numbers2

array([False, False, False, False])

In [61]:
numbers == numbers2

array([False, False, False, False])

In [63]:
grades = np.array([
    [85, 90, 95],
    [75, 80, 100],
    [77, 88, 99],
    [71, 81, 91]
])
grades

array([[ 85,  90,  95],
       [ 75,  80, 100],
       [ 77,  88,  99],
       [ 71,  81,  91]])

In [64]:
print(grades.sum()) # returns the sum of all elements in the array
print(grades.min()) # returns the minimum value in the array
print(grades.max()) # returns the maximum value in the array
print(grades.mean()) # returns the mean value of all elements in the array
print(grades.std()) # returns the standard deviation of all elements in the array
print(grades.var()) # returns the variance of all elements in the array
print(grades.sum(axis=0)) # returns the sum of each column in the array
print(grades.sum(axis=1)) # returns the sum of each row in the array
print(grades.mean(axis=0)) # returns the mean of each column in the array
print(grades.mean(axis=1)) # returns the mean of each row in the array


1032
71
100
86.0
9.03696114115064
81.66666666666667
[308 339 385]
[270 255 264 243]
[77.   84.75 96.25]
[90. 85. 88. 81.]


In [71]:
# universal functions (ufuncs)
numbers = np.array([1, 4, 9, 16, 36])
np.sqrt(numbers) # returns the square root of each element in the array 

array([1., 2., 3., 4., 6.])

In [72]:
numbers2 = np.arange(1, 6) + 10
numbers2

array([11, 12, 13, 14, 15])

In [73]:
np.add(numbers, numbers2) # adds the corresponding elements of the two arrays and returns a new array with the results

array([12, 16, 22, 30, 51])

In [74]:
# It is not multiplication, it is element-wise multiplication.
np.multiply(numbers, numbers2) # multiplies the corresponding elements of the two arrays and returns a new array with the results


array([ 11,  48, 117, 224, 540])

In [75]:
# indexing and slicing
grades = np.array([
    [85, 90, 95],
    [75, 80, 100],
    [77, 88, 99],
    [71, 81, 91]
])
grades

array([[ 85,  90,  95],
       [ 75,  80, 100],
       [ 77,  88,  99],
       [ 71,  81,  91]])

In [80]:
print(grades[0]) # returns the first row of the array
print(grades[1]) # returns the second row of the array
print(grades[0][0]) # returns the first element of the first row of the array
print(grades[0][1]) # returns the second element of the first row of the
print(grades[0][2]) # returns the third element of the first row of the array
print(grades[0:1]) # returns the first row of the array as a 2D array
print(grades[0:2]) # returns the first two rows of the array as a 2D array
print(grades[:, 0]) # returns the first column of the array
print(grades[:, 1]) # returns the second column of the array
print(grades[:, 2]) # returns the third column of the array
print(grades[0:2, 0:2]) # returns the first two rows and first two columns of the array as a 2D array
print(grades[1:3, 1:3]) # returns the second and third rows and second and third columns of the array as a 2D array
print(grades[0:3, 0:2]) # returns the first three rows and first two columns of the array as a 2D array

[85 90 95]
[ 75  80 100]
85
90
95
[[85 90 95]]
[[ 85  90  95]
 [ 75  80 100]]
[85 75 77 71]
[90 80 88 81]
[ 95 100  99  91]
[[85 90]
 [75 80]]
[[ 80 100]
 [ 88  99]]
[[85 90]
 [75 80]
 [77 88]]


In [81]:
copyGrades = grades.copy()
copyGrades

array([[ 85,  90,  95],
       [ 75,  80, 100],
       [ 77,  88,  99],
       [ 71,  81,  91]])

In [82]:
flattend = grades.flatten() # returns a 1D array containing all the elements of the original array
flattend

array([ 85,  90,  95,  75,  80, 100,  77,  88,  99,  71,  81,  91])

In [84]:
grades.T #

array([[ 85,  75,  77,  71],
       [ 90,  80,  88,  81],
       [ 95, 100,  99,  91]])

In [85]:
# Stacking
# Horizonatal stacking
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
np.hstack((a, b)) # stacks the two arrays horizontally (column-wise)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [86]:
# Vertical stacking
np.vstack((a, b)) # stacks the two arrays vertically (row-wise)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#