# numpy array from dict object
A **NumPy array** is primarily created from a **Python list** or a **tuple**.

It is **not** directly created from a standard Python **dictionary** in the same way.

***

## How NumPy Arrays are Created

* **From Python Lists or Tuples:** This is the most common way. The list or tuple provides the sequence of elements that will form the array.
    $$\text{np.array}([1, 2, 3]) \quad \text{or} \quad \text{np.array}((4, 5, 6))$$

* **From Dictionaries (Indirectly):** While you can't pass a dictionary directly to `np.array()` to get a standard numerical array, you can:
    1.  Create an array from its **keys**: $$\text{np.array}(my\_dict.\text{keys()})$$
    2.  Create an array from its **values**: $$\text{np.array}(my\_dict.\text{values()})$$
    3.  Create an array of **tuples** from its **items** (key-value pairs): $$\text{np.array}(my\_dict.\text{items()})$$

A NumPy array is a grid of values, all of the same type, and is built to hold sequential, ordered data, which aligns with the structure of lists and tuples, but not with the key-value structure of a dictionary. 

In [1]:
import numpy as np
import pandas as pd

In [2]:
# 🧱 Case 1: Dictionary of scalar values
# NumPy will treat the dictionary as a sequence of keys and values:

data = {'a': 10, 'b': 20, 'c': 30}

arr1 = np.array(list(data.keys()))
print(arr1)

arr2 = np.array(list(data.values()))
print(arr2)

arr3 = np.array(list(data.items()))
print(arr3)


['a' 'b' 'c']
[10 20 30]
[['a' '10']
 ['b' '20']
 ['c' '30']]


In [5]:
# 🧩 Case 2: Dictionary of lists (most common)
# If each key maps to a list (and lists are of the same length), you can convert it to a structured NumPy array.

data = {
    "name": ["Ali", "Zain", "Babar"],
    "marks": [55, 80, 60]
}

arr = np.array(list(zip(data["name"], data["marks"])))
print(arr)


[['Ali' '55']
 ['Zain' '80']
 ['Babar' '60']]


In [5]:
# 🧮 Case 3: Dictionary of lists → NumPy structured array (for labeled data)
# You can create a **structured array** with named columns.

data = {
    "name": ["Ali", "Zain", "Babar"],
    "marks": [55, 80, 60]
}

arr = np.array(
    list(zip(data["name"], data["marks"])),
    dtype=[('name', 'U10'), ('marks', 'i4')]
)

print(arr)
print(arr['name'])
print(arr['marks'])

[('Ali', 55) ('Zain', 80) ('Babar', 60)]
['Ali' 'Zain' 'Babar']
[55 80 60]


In [6]:
# 🧠 Pro Tip
# If your dictionary looks like a **table** (keys = columns, values = lists), you’ll often find it **easier to use pandas**:

import pandas as pd

df = pd.DataFrame(data)
print(df)


# Then you can convert it to NumPy easily:


arr = df.to_numpy()
print(arr)

    name  marks
0    Ali     55
1   Zain     80
2  Babar     60
[['Ali' 55]
 ['Zain' 80]
 ['Babar' 60]]


In [8]:
# **nested dictionaries** (e.g., dictionary of dictionaries → array or table)?

# Profile of students
# Outer keys (Ali, Zain, Babar) = rows (records)
# Inner keys (marks, age) = columns (attributes)

data = {
    'Ali': {'marks': 55, 'age': 20},
    'Zain': {'marks': 80, 'age': 21},
    'Babar': {'marks': 60, 'age': 22}
}

# required output array
# [[55 20] 
#  [80 21]
#  [60 22]]

# ✅ Now each row corresponds to one student, and each column to a property (marks, age).

In [9]:
# Option 1: Convert to NumPy array manually
# You can extract the inner values using list():

arr = np.array([list(d.values()) for d in data.values()])
print(arr)

# If you also want the column names, store them separately:
columns = list(next(iter(data.values())).keys())
print(columns)  # ['marks', 'age']

[[55 20]
 [80 21]
 [60 22]]
['marks', 'age']


In [10]:
# Option 2: Use pandas (easier for labeled data)

df = pd.DataFrame(data).T   # Transpose to make outer keys rows
print(df)


# then Convert to NumPy:
arr = df.to_numpy()
print(arr)

       marks  age
Ali       55   20
Zain      80   21
Babar     60   22
[[55 20]
 [80 21]
 [60 22]]


In [11]:
# ⚙️ Option 3: Structured NumPy Array (with names)
# If you want a pure NumPy structured array (like a mini-database table):

dtype = [('name', 'U10'), ('marks', 'i4'), ('age', 'i4')]
records = [(k, v['marks'], v['age']) for k, v in data.items()]
arr = np.array(records, dtype=dtype)

print(arr)
print(arr['name'])
print(arr['marks'])

[('Ali', 55, 20) ('Zain', 80, 21) ('Babar', 60, 22)]
['Ali' 'Zain' 'Babar']
[55 80 60]


In [12]:
# reverse this process — convert a NumPy array back into a dictionary (like data above)?
# convert a NumPy array back into a dictionary.
# We’ll look at 3 main cases depending on what kind of array you have.


In [13]:
# 🧱 Case 1: Simple 2D NumPy Array (no column names)

arr = np.array([
    [55, 20],
    [80, 21],
    [60, 22]
])

names = ['Ali', 'Zain', 'Babar']
columns = ['marks', 'age']

# Convert back to dictionary:

data = {
    name: {col: value for col, value in zip(columns, row)}
    for name, row in zip(names, arr)
}

print(data)


{'Ali': {'marks': np.int64(55), 'age': np.int64(20)}, 'Zain': {'marks': np.int64(80), 'age': np.int64(21)}, 'Babar': {'marks': np.int64(60), 'age': np.int64(22)}}


In [14]:
# 🧩 Case 2: Structured NumPy Array

# If your array was created with named fields (like this one 👇):
dtype = [('name', 'U10'), ('marks', 'i4'), ('age', 'i4')]
arr = np.array([
    ('Ali', 55, 20),
    ('Zain', 80, 21),
    ('Babar', 60, 22)
], dtype=dtype)

# Then you can easily turn it back into a dictionary:
data = {
    row['name']: {'marks': int(row['marks']), 'age': int(row['age'])}
    for row in arr
}

print(data)


{np.str_('Ali'): {'marks': 55, 'age': 20}, np.str_('Zain'): {'marks': 80, 'age': 21}, np.str_('Babar'): {'marks': 60, 'age': 22}}


In [15]:
# 📊 Case 3: If You Used pandas

# if your data passed through a pandas DataFrame:
df = pd.DataFrame({
    'name': ['Ali', 'Zain', 'Babar'],
    'marks': [55, 80, 60],
    'age': [20, 21, 22]
})

# You can convert back to dictionary directly:
data = df.set_index('name').to_dict(orient='index')
print(data)




{'Ali': {'marks': 55, 'age': 20}, 'Zain': {'marks': 80, 'age': 21}, 'Babar': {'marks': 60, 'age': 22}}


In [17]:
# Universal helper function that can automatically detect the array type (structured or normal) and convert it into a dictionary?

# 🔥 — here’s a universal helper function that can automatically detect whether your NumPy array is:
# a structured array (with named fields), or
# a regular 2D array (with column names and row labels provided),
# and convert it neatly back into a Python dictionary.

def numpy_to_dict(arr, row_keys=None, col_names=None):
    """
    Converts a NumPy array into a dictionary.
    
    Works for both structured and normal 2D arrays.
    
    Parameters:
    -----------
    arr : np.ndarray
        The input NumPy array.
    row_keys : list, optional
        Row labels (e.g., names like ['Ali', 'Zain']).
        Required for normal 2D arrays.
    col_names : list, optional
        Column labels (e.g., ['marks', 'age']).
        Required for normal 2D arrays.
    """
    # 🧱 Case 1: Structured array (has field names)
    if arr.dtype.names:
        return {
            str(row[arr.dtype.names[0]]): {
                name: (int(row[name]) if np.issubdtype(arr[name].dtype, np.integer)
                       else row[name])
                for name in arr.dtype.names[1:]
            }
            for row in arr
        }

    # 🧩 Case 2: Normal 2D array (needs keys & column names)
    elif arr.ndim == 2 and row_keys is not None and col_names is not None:
        return {
            rkey: {cname: value for cname, value in zip(col_names, row)}
            for rkey, row in zip(row_keys, arr)
        }

    else:
        raise ValueError(
            "For non-structured arrays, you must provide row_keys and col_names."
        )

# Example 1: Structured Array
dtype = [('name', 'U10'), ('marks', 'i4'), ('age', 'i4')]
arr = np.array([
    ('Ali', 55, 20),
    ('Zain', 80, 21),
    ('Babar', 60, 22)
], dtype=dtype)

data = numpy_to_dict(arr)
print(data)


# Example 2: Regular 2D Array
arr = np.array([
    [55, 20],
    [80, 21],
    [60, 22]
])
names = ['Ali', 'Zain', 'Babar']
cols = ['marks', 'age']

data = numpy_to_dict(arr, row_keys=names, col_names=cols)
print(data)


{'Ali': {'marks': 55, 'age': 20}, 'Zain': {'marks': 80, 'age': 21}, 'Babar': {'marks': 60, 'age': 22}}
{'Ali': {'marks': np.int64(55), 'age': np.int64(20)}, 'Zain': {'marks': np.int64(80), 'age': np.int64(21)}, 'Babar': {'marks': np.int64(60), 'age': np.int64(22)}}


In [18]:
# Create a bidirectional function — so the same function can also convert a dictionary to a NumPy array automatically?
# ✅ convert a Python dictionary → NumPy array, and
# ✅ convert a NumPy array → dictionary automatically.

def dict_numpy_converter(data, row_keys=None, col_names=None):
    """
    Converts between Python dictionary and NumPy array (both directions).

    - If input is a dictionary → returns a NumPy array.
    - If input is a NumPy array → returns a dictionary.

    Parameters
    ----------
    data : dict or np.ndarray
        Input data to convert.
    row_keys : list, optional
        Row labels for 2D NumPy arrays (when converting NumPy → dict).
    col_names : list, optional
        Column names for 2D NumPy arrays (when converting NumPy → dict).
    """
    
    # 🧩 CASE 1: Dictionary → NumPy array
    if isinstance(data, dict):
        first_val = next(iter(data.values()))

        # Case: dictionary of dictionaries
        if isinstance(first_val, dict):
            col_names = list(first_val.keys())
            row_keys = list(data.keys())
            arr = np.array([list(v.values()) for v in data.values()])
            return arr, row_keys, col_names

        # Case: dictionary of scalars
        else:
            arr = np.array(list(data.items()))
            return arr, ['key', 'value'], None

    # 🧱 CASE 2: NumPy array → Dictionary
    elif isinstance(data, np.ndarray):
        # Structured array
        if data.dtype.names:
            return {
                str(row[data.dtype.names[0]]): {
                    name: (int(row[name]) if np.issubdtype(data[name].dtype, np.integer)
                           else row[name])
                    for name in data.dtype.names[1:]
                }
                for row in data
            }

        # Normal 2D array (needs names)
        elif data.ndim == 2 and row_keys and col_names:
            return {
                rkey: {cname: value for cname, value in zip(col_names, row)}
                for rkey, row in zip(row_keys, data)
            }

        else:
            raise ValueError(
                "For non-structured arrays, please provide row_keys and col_names."
            )

    else:
        raise TypeError("Input must be either a dict or a NumPy ndarray.")

    
# Example 1: Dictionary → NumPy array
    data = {
    'Ali': {'marks': 55, 'age': 20},
    'Zain': {'marks': 80, 'age': 21},
    'Babar': {'marks': 60, 'age': 22}
}

arr, row_keys, col_names = dict_numpy_converter(data)
print(arr)
print(row_keys)
print(col_names)

# Example 2: NumPy array → Dictionary
data_back = dict_numpy_converter(arr, row_keys=row_keys, col_names=col_names)
print(data_back)

# Example 3: Structured array → Dictionary
dtype = [('name', 'U10'), ('marks', 'i4'), ('age', 'i4')]
arr_struct = np.array([
    ('Ali', 55, 20),
    ('Zain', 80, 21),
    ('Babar', 60, 22)
], dtype=dtype)

data_back = dict_numpy_converter(arr_struct)
print(data_back)



[[55 20]
 [80 21]
 [60 22]]
['Ali', 'Zain', 'Babar']
['marks', 'age']
{'Ali': {'marks': np.int64(55), 'age': np.int64(20)}, 'Zain': {'marks': np.int64(80), 'age': np.int64(21)}, 'Babar': {'marks': np.int64(60), 'age': np.int64(22)}}
{'Ali': {'marks': 55, 'age': 20}, 'Zain': {'marks': 80, 'age': 21}, 'Babar': {'marks': 60, 'age': 22}}
